### ISSUE TITLE
Using pokemon.json is very inefficient

### ISSUE THREAD

**Issue by AalbatrossGuy** [Jimmy-Blue/Articuno#11]
Use a Pokemon papi or something...don't use json...an api is much faster than 30k lines of json :/

**Comment by B1ue-Dev** [comment]
This got discussed in the r/Pokemon server previously. I did plan to use an API, however, an API cannot provide local json read, which just takes away the ability to autocorrect on looking up for a Pokemon. I do use API from multiple sources for different information though, not just stats. :/
