### ISSUE TITLE
Ability to see what time it is in other time zones (feature want to add)

### ISSUE THREAD

**Issue by kxws** [Jimmy-Blue/Articuno#14]
It would be cool for something like `/time country:` to exist. Lets say, you live in america and want to check the time in Greece, you would use that command and it would tell you the time.

A bit of a useless command but i dont know how to add it myself

**Comment by B1ue-Dev** [comment]
You can use time and datetime to get the current time in the region. I may (or not) add it. Depends on whenever I think it should be added or not.

**Comment by ghost** [comment]
Maybe I can try to implement this. It also would have a time zone calculator that tells what time it is in 5 hours.

**Comment by B1ue-Dev** [comment]
Forgive me for forgetting about this.

I don't think this is something that I will consider adding to the bot.
