### ISSUE TITLE
[REQUEST]  Re-add emoji management system with slash command

### ISSUE THREAD

**Issue by ghost** [Jimmy-Blue/Articuno#4]
Add a emoji stealer command again. I miss it.

**Comment by B1ue-Dev** [comment]
I will consider adding this again, once I finish with the core part.

**Comment by kxws** [comment]
I agree. This would be cool

**Comment by B1ue-Dev** [comment]
This will be added in the next PR. It is currently under development now.

**Comment by B1ue-Dev** [comment]
Added with #13.
