### ISSUE TITLE
About your `/help` command...

### ISSUE THREAD

**Issue by nattadasu** [Jimmy-Blue/Articuno#42]
Heya! I noticed while exploring some interactions.py repos ~~to look some inspiration on how implementing help command~~... your `/help` command wouldn't index last commands since [you're using multiples of 10 in your `i` var](https://github.com/B1ue-Dev/Articuno/blob/master/exts/core/help.py#L29-L37), so it'd orphan some commands, like if you have 36 commands, embed only shows 30 commands instead. Then those commands aren't sorted alphabetically globally, but per pages.

I tried to patch using what I've wrote similarly, but with languages index, and it works properly. Below is my patch, feel free to use it :D

```py
@interactions.slash_command(
    name="help",
    description="Get a list of all available commands."
)
async def help(self, ctx: interactions.SlashContext) -> None:
    """Get a list of all available commands."""
    help_list = []
    commands = sorted(self.client.application_commands,
                      key=lambda x: str(x.name))

    for i in range(0, len(commands), 10):
        listed = []
        for command in commands[i:i + 10]:
            cmd_name = f"/{command.name}"
            group_name = f" {command.group_name}" if command.group_name else ""
            sub_cmd_name = f" {command.sub_cmd_name}" if command.sub_cmd_name else ""
            name = f"{cmd_name}{group_name}{sub_cmd_name}"
            description = command.sub_cmd_description if command.sub_cmd_name else command.description
            listed.append(interactions.EmbedField(name=name, value=description))

        help_list.append(
            interactions.Embed(
                title="List of available commands.",
                color=0x7CB7D3,
                thumbnail=interactions.EmbedAttachment(
                    url=self.client.user.avatar.url),
                fields=listed
            )
        )

    paginator = Paginator.create_from_embeds(
        self.client, *help_list, timeout=30)
    await paginator.send(ctx)
```

For this, I used `range()` as it will do the same job with `i = 0; i +=1` stuff, but better and makes the code even smaller.

**Comment by B1ue-Dev** [comment]
Hey! First, thanks for your contribution, I am very appreciated. 🥰

If possible, would you mind creating a PR that target the unstable branch? I want your contribution to display on the bot page as well.

I tested the code and have some suggestions.

```py
            listed = []
            for command in commands[i:i + 10]:
                if type(command) is interactions.SlashCommand:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

You should include this line to actually checks if the command is a `SlashCommand` one or can be `ContextMenu` one, in this case, we only need to display a list of slash commands, so need a check there.

```py
                    name = f"{cmd_name}{group_name}{sub_cmd_name}"
                    description = command.sub_cmd_description if command.sub_cmd_name else command.description
                    listed.append((interactions.EmbedField(name=f"{name}", value=f"{description}")))
                                                                ^^^^^^^^^        ^^^^^^^^^^^^^^^^^
```

These two should be used as a f-string, since for some unknown reasons, it will complain if we don't have a f-string.
```py
  File "/home/blue/.local/lib/python3.11/site-packages/interactions/models/discord/embed.py", line 62, in _value_validation
    if len(value) > EMBED_FIELD_VALUE_LENGTH:                                                                                                            
       ^^^^^^^^^^
TypeError: object of type 'LocalisedDesc' has no len()
```

Oh, and remember to format your code with black and flake8 as well, so it meets the contribution requirement. Happy coding!

**Comment by nattadasu** [comment]
> would you mind creating a PR that target the unstable branch? 

Sure, I'll submit a PR soon.

> These two should be used as a f-string, since for some unknown reasons, it will complain if we don't have a f-string.

Huh, I just noticed that as well, weird that Windows allows it for some reason when I'm experimenting with it.

Switched to my server, and it seems it broke as well 🤔
